line/promgen

- .gitignore
- lib/injector.rb
Fix a following warning and enable frozen_string_literal:
```sh
$ find . | grep -e '\.rb$' | xargs ruby -w
./lib/injector.rb:25: warning: `frozen_string_literal' is ignored after any tokens
```
> Enable frozen_string_literal

- README.md
- lib/promgen/alert/sender/ikachan.rb
- test/promgen/test_alert.rb
Problem
--
In case of alerting uses ikachan with HipChat through `/notice` API endpoint, it cannot fire the mentioned message to user(s) (e.g. `Alert: @here`).
Way to solve
--
Support to switch the API endpoint through the environment variable `HIPCHAT_PRIVMSG`.
If `HIPCHAT_PRIVMSG` is set, promgen alerting uses `/privmsg` endpoint of ikachan. `/privmsg` endpoint can fire the mentioned message.
> Support HipChat's privmsg for alerting by ikachan

- README.md
- config.ru
- config.sample.yml
This allows the password to be handled by a configuration management tool (like ansible/chef/etc) instead of within Promgen. This should simplify things for deployment.
> Read Rack::Auth::Basic password out of config file

- lib/promgen/web/route/project_route.rb
- lib/promgen/web/route/service_route.rb
- views/list_services.erb
- views/show_project.erb
- views/show_service.erb
Since the main / page can get very long after many service and projects have been added, it's useful to have a page to only view a single service by itself
> Add a page to show a single service with it's list of projects

- config.sample.yml
- lib/promgen/web.rb
- lib/promgen/web/route/project_exporter_route.rb
- views/register_project_exporter.erb
This allows a team to set the commonly used exporters in the config file.
```yml
default_exporters:
node: 9100
nginx: 9113
mysqld: 9104
apache: 9117
```
> Set default exporter list from config

- config.ru
Later I would like to implement some promgen specific metrics (particularly on Alert::Sender delivery) but in the mean time, I thought it would be good to have an empty /metrics route so that I could take advantage of Prometheus and a basic InstanceDown rule to ensure that Promgen is running
> Metrics stub to allow Prometheus to check up/down status

- Gemfile
- Gemfile.lock
- lib/promgen.rb
- lib/promgen/repo/audit_repo.rb
- lib/promgen/service/audit_service.rb
- lib/promgen/web.rb
- lib/promgen/web/route/audit_route.rb
- lib/promgen/web/route/project_exporter_route.rb
- lib/promgen/web/route/project_route.rb
- lib/promgen/web/route/rule_route.rb
- lib/promgen/web/route/service_route.rb
- migrations/10_audit_log.rb
- test/promgen/web/route/test_audit_log_route.rb
- views/audit_log.erb
- views/layout.erb
There are probably various style bits that will need to be fixed, but this adds a new audit log page to see what actions have been changed recently.
One place that I need feedback on, is the specific content of some of the logging messages, though some of that can be handled in a different pull request
> Audit log page

- lib/promgen/config_writer.rb
- lib/promgen/repo/project_exporter_repo.rb
- lib/promgen/repo/project_repo.rb
- lib/promgen/web/route/project_exporter_route.rb
- migrations/11_metrics_path.rb
- migrations/5_exporter.rb
- test/promgen/repo/test_project.rb
- test/promgen/repo/test_project_exporter.rb
- test/promgen/test_config_writer.rb
- test/promgen/web/route/test_project_exporter_route.rb
- views/list_services.erb
- views/register_project_exporter.erb
- views/register_rule.erb
- views/show_project.erb
- views/show_service.erb
Apply this change will make metrics path configurable, this will output json file like
```
{
"targets":[
"localhost:5000"
],
"labels":{
"service":"foo",
"project":"bar",
"farm":"hoge",
"job":"hogehoge",
"__metrics_path__":"/internal/metrics"
}
}
```
> Make metrics path configurable

- lib/promgen/rule_writer.rb
- lib/promgen/web/route/api_route.rb
By refactoring our rule_writer a bit, we can return our rules file from
the API in the same format that we write it to file
> Add rule_writer.render so we can use that in our API

- .rubocop.yml
- lib/promgen/repo/project_exporter_repo.rb
- migrations/11_metrics_path.rb
- migrations/5_exporter.rb
Although rubocop points out test/promgen/test_config_writer.rb, I think that test/promgen/test_config_writer.rb is valid. So I change .rubocop.yml.
```
$ rubocop
Inspecting 93 files
.....................C................................C....C...................C.............
Offenses:
lib/promgen/repo/project_exporter_repo.rb:66:81: C: Space missing after colon.
if @db[:project_exporter].where(project_id: project_id, port: port, path:path).count == 0
^
migrations/11_metrics_path.rb:28:48: C: Use the new Ruby 1.9 hash syntax.
drop_constraint(:unique_project_id_port, :type => :unique)
^^^^^^^^
migrations/11_metrics_path.rb:29:58: C: Use the new Ruby 1.9 hash syntax.
add_unique_constraint([:project_id, :port, :path], :name => :unique_project_id_port_path)
^^^^^^^^ …
```
> Modify to resolve rubcop inspection

- README.md
- config.ru
- config.sample.yml
- lib/promgen.rb
- lib/promgen/api.rb
- lib/promgen/config_writer.rb
- lib/promgen/rule_writer.rb
- lib/promgen/web.rb
- public/css/promgen.css
- test/promgen/test.rb
- test/promgen/test_api.rb
- test/promgen/web/test_api.rb
- views/api.erb
- views/layout.erb
Since Promgen manages the configuration file for Prometheus, it’s normal for Promgen and Prometheus to be paired together on the same server. Once you have multiple servers for load balancing and failover, it becomes more difficult to keep the configuration files in sync.
This pull request adds two enhancements.
1) POSTing to /api/v1/config and /api/v1/rule/ will trigger to Promgen to write it’s configuration changes to disk.
2) Add notification hooks to config_writer and rule_writer to POST updates to configured endpoints on updates.
```yaml
config_writer:
path: /tmp/prom.json
notify:
- http://promgen.other/api/v1/config
rule_writer:
rule_path: /tmp/prom.rule
promtool_path: /path/to/promtool
notify:
- http://promgen.other/api/v1/rule/
```
Assuming that each Promgen instance shares the …
> Trigger write api

- lib/promgen/web/route/host_route.rb
- lib/promgen/web/route/project_exporter_route.rb
- lib/promgen/web/route/project_route.rb
- views/add_host.erb
- views/register_project_exporter.erb
- views/show_rule.erb
- views/update_project.erb
Service was missing on a few pages, so this should fix it to show the proper hierarchy
Home
Home > Service
Home > Service > Project
Home > Service > Project > etc
> Fix the breadcrumbs to show the full hierarchy

- lib/promgen/web/route/rule_route.rb
- migrations/13_rule_text_length.rb
```
$ rubocop
Inspecting 96 files
................................................C........C......................................
Offenses:
lib/promgen/web/route/rule_route.rb:36:32: C: Do not use parentheses for method calls with no arguments.
@rule = Promgen::Rule.new()
^
migrations/13_rule_text_length.rb:26:43: C: Use the new Ruby 1.9 hash syntax.
set_column_type :if_clause, String, :text=>true
^^^^^^^
migrations/13_rule_text_length.rb:26:48: C: Surrounding space missing for operator =>.
set_column_type :if_clause, String, :text=>true
^^
migrations/13_rule_text_length.rb:27:47: C: Use the new Ruby 1.9 hash syntax.
set_column_type :labels_clause, String, :text=>true
^^^^^^^
migrations/13_rule_text_length.rb:27:52: C: Surrounding space missing for operator =>.
set_column_type …
```
> Fix robucop inspection result

- README.md
I was going to install promgen according to "Getting started" in README.md.
However, many errors occurred.
As a result of trial and error, I successfully installed it, so Pull Request does it.
The modifications are listed below.
- fix specified docker repository:tag. `promgen:latest` -> `line/promgen:master`
`promgen:latest` [does not exist](https://hub.docker.com/r/line/promgen/tags/).  I suggest to make `latest` tag (According to convention of docker.)
- remove `--network host`. 
Generally, port may overlap with host machine, I think that `--network host` should be avoided.
- add `chmod 777 ~/.config/promgen`.  
If do not do this, Permission denied has occurred.
```
/usr/src/app/promgen/settings.py:37: UserWarning: Unset SECRET_KEY setting to random for now
warnings.warn('Unset …
```
> fixed "Getting started" manual.

- Dockerfile
I noticed that the docker image doesn't contain `promtool`, even though it is required for rule checking by the web app.
I extended the Dockerfile to download `promtool` from the current Prometheus release binaries (that is [v2.1.0](https://github.com/prometheus/prometheus/releases)) and place it in `/usr/local/bin/promtool`.
Note: This PR contains the Prometheus version hard-coded in the Dockerfile. Alternatively, the latest version could be fetched using the Github API.
> Dockerfile: Ship promtool in docker image

- promgen/notification/slack.py
- promgen/templates/promgen/sender/slack.body.txt
- promgen/templates/promgen/sender/slack.resolved.txt
- setup.py
Added slack notifier.
The notifier requires a [Slack Webhook](https://api.slack.com/incoming-webhooks) to be configured in advance.
> Added slack notifier

- promgen/management/commands/rules.py
- promgen/prometheus.py
- promgen/tests/examples/promgen.yml
- promgen/tests/test_rules.py
Updated test cases and ensure that render_rules always works with bytes
to handle this mismatch between using yaml.safe_dump with utf8 and
json.dump
This expands on the bit that @seoester filed in #39 along with ensuring our test cases and django management command still work and handle things properly
> Fix bytes/str mismatch with writing rules

- promgen/settings.py
The change allows setting the environment variable DEBUG to any value except '0' to enable the django debug mode.
Placing a non-empty file `DEBUG` in the `CONFIG_DIR` has the same effect (the file is loaded by the `envdir` module).
Note: Previously it was possible to enable the debug mode by leaving the `DEBUG` file empty. This would **not** be possible anymore after merging this PR.
Personally, I think it is worth breaking this functionality for higher compatibility with `envdir` and to keep the code more maintainable.
However, if you'd prefer to keep this feature, please get back to me.
> Enable debug mode when environment variable DEBUG is set

- promgen/forms.py
- promgen/views.py
* Rename to fix descriptions
- ServiceForm -> ServiceUpdate
- ProjectMove -> ProjectUpdate
- ProjectForm -> ProjectRegister
* Add missing ServiceRegister
* Fix ServiceRegister to use the correct ServiceRegister
Should fix #53 reported by @seoester
> Fix display message when registering a duplicate Service

- promgen/__init__.py
- promgen/management/commands/bootstrap.py
- promgen/settings.py
* Rename CONFIG_DIR to PROMGEN_CONFIG_DIR to be more descriptive
* Add PROMGEN_CONFIG as the path to promgen.yml
* Add STATIC_ROOT (was unintentionally hardcoded)
* Move SECRET_KEY within settings.py to allow override in promgen.yml
STATIC_ROOT was missed and I've updated PROMGEN_CONFIG_DIR based on a comment in #54
@seoester let me know if this seems reasonable to you regarding your documentation changes.
> Updates to CONFIG_DIR, and STATIC_ROOT

- promgen/static/js/promgen.js
- promgen/templates/promgen/rule_form_block.html
When proxying over several prometheus servers, this can cause the rule
editor to slow down the entire page. While it's annoying to remove
features, it's probably simplest to disable this feature for a single
release until there's more time to implement it in a better way.
I hope to bring this back soon, but want to disable this so I can cut a new version
> Temporarily disable pending refactoring

- CONTRIBUTING.md
This pull request updates the "Setting up Promgen for development" section in the CONTRIBUTING file.
I added some commands initialising the required settings and also switched from `virtualenv` to the `venv` module.
> Update instructions in CONTRIBUTING.md

- promgen/static/css/promgen.css
- promgen/templates/base.html
- promgen/templates/promgen/ajax_clause_check.html
- promgen/templates/promgen/rule_form_block.html
- promgen/templates/promgen/rule_update.html
This should help reduce a bit of confusion when dealing with rule overrides
> Show warning when parent rule is missing <exclude> macro

- docker/docker-entrypoint.sh
This PR adds parameters via env variables to the `docker-compose-bootstrap` shortcut command.
This enables setting the values in the `environment` stanza of a docker-compose file.
> Parameterise docker-compose-bootstrap using env vars

- promgen/prometheus.py
- promgen/templates/promgen/rule_update.html
Since our rendered yaml file is now utf8 encode, we need to make sure to
decode it when showing our exception
> Fix for missing promtool validation error

- promgen/management/commands/prune-alerts.py
Combined with the new notifier queue in #94 add a prune command so we can avoid having our database grow too much
> Add prune-alerts command

- promgen/signals.py
- promgen/views.py
This should reduce confusion if a user subscribes to a project/service but does not already have notifications subscribe. It will default to using owner.email to create a notification or print a warning if it does not exist
> When a user subscribes, ensure they have a default notifier configured

- promgen/static/js/promgen.vue.js
Removes some custom logic that was likely wrong and simplify using native javascript filter and map functions
> [BUGFIX] Fix computed labels

- promgen/proxy.py
- promgen/templates/promgen/rule_form_block.html
- promgen/urls.py
Support for Grafana adhoc filters
> [IMPROVEMENT] Add proxy for /api/v1/labels

- .circleci/config.yml
- Dockerfile
- promgen/forms.py
- promgen/prometheus.py
- promgen/templates/promgen/rule_update.html
- promgen/tests/test_rules.py
- promgen/views.py
- setup.cfg
Removes some duplicated code and consolidates the promtool rule validation into a single place for more consistent error handling
> [BUGFIX] Move promtool validation into RuleForm.clean

- promgen/forms.py
- promgen/templates/promgen/rule_formset_table.html
- promgen/templates/promgen/rule_update.html
- promgen/views.py
* Move Formset fields to forms module to better group code
* Factor out formset template for consistency
* Validate labels and annotations django side, then try rendering. This requires knowing how cached_properly is used so that we can validate Django side, and then validate with Promtool, before actually saving
> [BUGFIX] Refactor rule validation to take into account labels and annotations

- promgen/management/commands/rules.py
- promgen/management/commands/targets.py
- promgen/management/commands/urls.py
- promgen/prometheus.py
- promgen/signals.py
- promgen/tasks.py
- promgen/tests/test_routes.py
- promgen/views.py
More cleanly split tasks.py and prometheus.py in preparation for additional cleanup and refactoring
> [INTERNAL] Move remaining celery tasks to tasks.py

- promgen/templates/promgen/alert_row.html
- promgen/templates/promgen/rule_block.html
- When listing rules, show rule specific labels
- Labels on Rule settings colored as -primary
- Labels on Alerts colored as -danger
- Labels on Silences colored as -warning
> When listing rules, show rule specific labels

- docker/prometheus.yml
- promgen/prometheus.py
- promgen/templates/promgen/project_detail_urls.html
Use the `module` as a `job` label, to better match exporters, and use the combination of `job` and `instance` to allow muting a `blackbox_exporter` probe
> Add silence button to blackbox exporter entries

- promgen/tests/__init__.py
- promgen/tests/test_rules.py
- promgen/views.py
- Add test cases for each scenario
- Refactor settings for add_user_permissions
- Ensure rule is registered with correct ContentType
> Fix rule import

- promgen/prometheus.py
- promgen/templates/promgen/rule_update.html
- promgen/templatetags/promgen.py
- promgen/tests/test_rules.py
- promgen/views.py
> [INTERNAL] Refactor macro for common use case

- Dockerfile
Use `--no-cache` with `apk add` and remove `apk update` to prevent
leaving any local cache files in the immediate layers, which will make
the Docker image more slim/light.
> Refactor apk commands in Dockerfile

- Dockerfile
- docker-compose.yml
- docker/docker-entrypoint.sh
- Change docker-entrypoint to use /bin/sh
- Leave mariadb-dev and postgressql-dev installed for shared libraries
Fixes #173
> [BUGFIX] Fixes for Docker build

- promgen/views.py
While the route was updated in #167, this check was never updated
Fixes #177
> [BUGFIX] pk should always be an integer

- promgen/forms.py
- promgen/views.py
- Move validation into forms.HostForm
- Minor refactoring of views.HostRegister
> Fix hostname validation

- Pipfile.lock
- docker/requirements.txt
- promgen/tests/__init__.py
- promgen/tests/test_api.py
- promgen/tests/test_host_add.py
- promgen/tests/test_routes.py
- promgen/tests/test_rules.py
- promgen/tests/test_silence.py
- promgen/tests/test_webhook.py
- setup.py
- Remove dependency on factory_boy
- Add assertRoute for checking routes and redirects
- Add add_force_login to simplfy auth checks
> Refactor unittests

- promgen/static/js/promgen.js
- promgen/static/js/promgen.vue.js
- promgen/templates/promgen/project_form.html
- promgen/templates/promgen/shard_header.html
Working on removing custom jquery and porting more to Vuejs
> Add <promql-query> tag

- docs/user/api.rst
The request method of ```/api/v1/alerts```  is POST.
https://github.com/line/promgen/blob/master/promgen/views.py#L1034
> Modify to the correct request method

- promgen/management/commands/rules.py
I found the following error when using ```promgen rules```.
```
$ promgen rules
Traceback (most recent call last):
File "/Users/shokada/src/line/promgenenv/bin/promgen", line 11, in <module>
load_entry_point('promgen', 'console_scripts', 'promgen')()
File "/Users/shokada/src/line/promgen/promgen/manage.py", line 20, in main
execute_from_command_line(sys.argv)
File "/Users/shokada/src/line/promgenenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
utility.execute()
File "/Users/shokada/src/line/promgenenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/Users/shokada/src/line/promgenenv/lib/python3.7/site-packages/django/core/management/ …
```
> Change stdout.write to stdout.buffer.write

- promgen/prometheus.py
Our current import code expects rules to typically be in the full rule
format (with groups) but there are places where we render just the rule.
This fix wraps the rule in a group when necessary
> [BUGFIX] Fix rule import

- promgen/models.py
Since we define most of our relations on our local proxy Site module,
we want to ensure our lookup does the same.
> [BUGFIX] Rule.content_object should use our Site proxy module

- promgen/prometheus.py
- promgen/renderers.py
- promgen/rest.py
- promgen/serializers.py
Refactor to use rest_framework Serializer so that we can better consolidate our logic for rendering (and prefetching) a list of Rule objects and rendering them in the correct format
> [INTERNAL] Refactored rule rendering to use Renderer and Serializer classes

- codecov.yml
The codecov report is sometimes useful as a glance to see how much is being covered, but we do not want it to fail our pull request because of it so change minimum coverage ratio to 0%.
https://docs.codecov.io/docs/commit-status#section-target
> Change minimum coverage ratio.

- docker/alertmanager.yml
Possibly the cause of confusion in #205
> [DOCUMENTATION] Fix reference to old endpoint

- promgen/rest.py
- promgen/templates/promgen/navbar.html
- promgen/urls.py
- Rename `/api` to `/rest` for Promgen specific endpoints
- Add `/rest/all/rules` to replace `/api/v1/rules` to export all rules
> [INTERNAL] Start refactoring api into `/rest/` namespace

- promgen/templates/promgen/rule_form_block.html
Adds missing `duration` label and minor fix to formatting
> [BUGFIX] Add missing duration label to rules page

- promgen/tasks.py
- promgen/views.py
Minor refactor of #250 with docs
This is to squash into a single commit with docs
> Fix race condition

- promgen/forms.py
RuleRegister is slightly overloaded so that if a regular Rule fails
validation, it tries again as an import. The Import form has two
optional fields so we were never returning the original duplicate name
error from the original Rule validation
> [BUGFIX] Fix missing error message with duplicate Rule name

- promgen/models.py
- promgen/views.py
The test classes were refactored in #243 but this instance was missed
> [BUGFIX] Fix test data for notifier test

- promgen/management/commands/bootstrap.py
- promgen/settings.py
- Since bootstrap is intended for operational engineers, we will trust
they have the URL format right, and not try to validate it
- Migrate settings to use pathlib
Fixes #51
> Bootstrap will only check for absence of required fields

- promgen/templates/promgen/exporter_form.html
- promgen/templates/promgen/project_detail_exporters.html
- promgen/tests/test_routes.py
- promgen/urls.py
- promgen/views.py
- Query based on project.id (instead of farm.id) for future refactoring
- Change from form to regular POST data to avoid extra validation confusion
- Simplify exporter-test button html
> Fix exporter test

- Makefile
Fixed the following error.
```
$ make clean
Removing venv
Clearing dist files
$ make run
python3 -m venv .venv
.venv/bin/pip pip -U pip
ERROR: unknown command "pip"
make: *** [.venv/bin/pip] Error 1
```
> Fix unknown command error

- promgen/apps.py
- promgen/checks.py
Hoping to use to solve parts of #266
> Use the django checks framework to diagnose errors

- promgen/__init__.py
- promgen/management/commands/bootstrap.py
- promgen/settings.py
This should help with part of the issues in #266 regarding the django `sites.Site` object and how it's used for building requests
> Cleanup `promgen bootstrap` and some settings

- promgen/checks.py
This method was originally a copy of the other directories check, but we need the `key` var for our error message. We also want to show the path to our configuration file to help with debugging
> Fix our check warning messages

- promgen/checks.py
- promgen/management/commands/bootstrap.py
The built in django [checks] framework runs automatically before many commands. This means that by default, they can't be used to check database objects, because they may be run pre-migrations. To solve this, we stop auto registering the checks that require database access, and only register them when we are specifically running our bootstrap scrip
[checks]: https://docs.djangoproject.com/en/3.0/topics/checks/#//apple_ref/Module/django.core.checks
> Fix checks

- promgen/static/js/promgen.vue.js
- promgen/templates/base.html
- promgen/templates/promgen/alert_row.html
- promgen/templates/promgen/global_messages.html
- promgen/templates/promgen/silence_form.html
- promgen/templates/promgen/silence_row.html
Promgen often needs to deal with three different template languages, `Djagno`, `Vue`, and `Go`, and they all use the same `{{ }}` pattern for declaring templates. This shows up frequently on the Django side, where the `{% verbatim %}` needs to be used to ensure that **Vue** templates are not accidentally interpreted as **Django** templates (this happened a lot in initial development.
Recently, there have been cases when **Go** templates were rendered out to HTML from the rule editor, and then mistakenly rendered by **Vue**, causing the **Vue** renderer to throw an error and leave the page blank.
1. Fix one part of the **Django**, **Vue**, **Go** template mismatch, by changing the delimiters used so that they do not conflict. (This will also remove the requirement to use `{% verbatim %}` …
> [BUGFIXES] Use alternate Vue delimiters to fix double rendering bugs

- promgen/templates/promgen/sender_row.html
The existing overflow hardcoding adds a confusing scrollbar. This should
make things less confusing to the user and fix some of the layout issues
> [BUGFIX] Fix overflow formatting for notifiers

- promgen/views.py
This PR fixes a typo in the 'No results' message (`verity` -> `verify`) and rewords the message a bit.
> Fix typo in 'No results' message

- CHANGELOG.md
- CONTRIBUTING.md
- Makefile
- README.md
In the near future, the `bootstrap` command still needs to likely be split up better, but this should make progress on a bit easier install
> Update install docs to mention Makefile

- Makefile
- README.md
- docker/docker-entrypoint.sh
- promgen/checks.py
- promgen/management/commands/bootstrap.py
The bootstrap command has an issue where it is difficult to both configure the settings and test at the same time, because there is no easy way to also reload the django settings. This means we need to separate the commands. We also want to run some tests that require the database, but we can't have them enabled by default or other commands like migrate will be stuck in a chicken/egg problem. To get around this we create a decorator to check for database access for our checks that require it.
This is a continuation of documentation fixes for #299 and should handle the issue in #302
> Split bootstrap checks

- Makefile
- docker-compose.yml
- promgen/apps.py
- promgen/checks.py
- setup.cfg
It's too fragile to run any kind of check that requires database, using the default [django.core.checks](https://docs.djangoproject.com/en/3.1/topics/checks#s-system-check-framework) framework.
[post_migrate](https://docs.djangoproject.com/en/3.1/ref/signals#s-post-migrate) does not have as pretty error messages, but we can be sure the rest of the database settings are correct.
Move the checks that require database to post_migrate, and we'll make the visible output better later.
Closes #302 #305
> Move checks that require database, to post_migrate

- promgen/templates/promgen/alert_detail.html
- promgen/templates/promgen/alert_list.html
- promgen/templates/promgen/audit_list.html
- promgen/views.py
This can probably be improved more in the future, but this formats the json into something *much* more readable
> Improved Alert View

- promgen/actions.py
- promgen/admin.py
- promgen/tasks.py
- promgen/templates/promgen/navbar.html
- promgen/urls.py
- promgen/views.py
Previously our "Commit" button was somewhat awkwardly placed, and only handled deploying targets. Move to an admin action and support deploying rules and urls as well.
> Move our "Commit" button to Admin actions

- README.md
I think it's better to have migration command to setup test environment.
Otherwise developer might execute  `docker-compose run web createsuperuser` 
before executing `docker-compose run web migrate`
> add databse migration command in README.md

- promgen/templates/promgen/alert_list.html
- promgen/templates/promgen/audit_list.html
- promgen/templates/promgen/home.html
- promgen/templates/promgen/project_detail_configuration.html
- promgen/templates/promgen/rule_detail.html
- promgen/templates/promgen/rule_update.html
- promgen/templates/promgen/service_block.html
- promgen/templates/promgen/service_header.html
- promgen/templates/promgen/service_list.html
- promgen/templatetags/promgen.py
Update History button for Edits and Alerts
- Add templatetag `urlqs` for making it easier to link to filtered pages
- Put Edit History and Alert History under combined Change History dropdown
> [IMPROVEMENT] Change history dropdown

- promgen/static/js/promgen.vue.js
- promgen/templates/promgen/global_alerts.html
- promgen/templates/promgen/global_silences.html
- promgen/templates/promgen/navbar.html
- promgen/templates/promgen/project_detail.html
- promgen/templates/promgen/rule_detail.html
- promgen/templates/promgen/rule_update.html
- promgen/templates/promgen/service_block.html
- promgen/templates/promgen/silence_form.html
This PR improves performance of rendering alerts and silences in Vue.
Currently, all alerts and silences are always rendered and hidden using the `collapse` CSS rule. This causes rendering delays on page load and whenever components need to be re-rendered (for example, on form input change; #370).
With changes introduced in this PR, all alerts and silences are now hidden behind `v-if`, so the HTML elements are not generated/rendered until the expression is truthy.
* Introduce `toggleComponent()`, which dynamically toggles the state of components
* The initial state of all components is falsy, so they're not shown by default
* Since the `components` object does not have any properties, it needs to be updated using `this.$set()`
* Use `toggleComponent()` for all elements that previously …
> [IMPROVEMENT] Improve performance of rendering alerts and silences

- promgen/static/js/promgen.js
- promgen/static/js/promgen.vue.js
- promgen/templates/promgen/alert_row.html
- promgen/templates/promgen/global_alerts.html
- promgen/templates/promgen/global_silences.html
- promgen/templates/promgen/navbar.html
- promgen/templates/promgen/project_detail.html
- promgen/templates/promgen/rule_detail.html
- promgen/templates/promgen/rule_update.html
- promgen/templates/promgen/service_block.html
This PR refactors the way alert and silence lists are rendered, by removing `v-if` from `v-for` directives. This way we avoid any runtime errors and unnecessary iterations.
* Update `computed` field to return `Map` instead of `Set`
* Use these new maps in `v-for` to avoid the need for additional filters
* Remove unused `index` variable in iterations
> [IMPROVEMENT] Improve list rendering in Vue

- promgen/templates/rest_framework/api.html
This PR fixes a JavaScript error about a missing CSRF token on the API page.
* Update `api.html` based on [`base.html`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/templates/rest_framework/base.html#L290-L295) in Django REST Framework, to include a CSRF token
> [BUGFIX] Missing CSRF token on API page

- promgen/__init__.py
When initially installing Promgen, envdir may not already be installed, but this path gets resolved trying to read the version from `promgen.version`.
> [BUGFIX] envdir import fix

- promgen/tests/test_host_add.py
- promgen/validators.py
Our previous fix (in #380) was too naive, and forgets `.` and other characters that can be in a hostname. May be better to base it on the existing URLValidator
> [BUGFIX] Hostname validator based off URLValidator

- promgen/templates/promgen/notifier_form.html
While the missing div tag is likely from a change several years ago, the recent changes our Vuejs code have caused parts of the code to be (correctly) more strict, causing this error to become visible on the notifier edit page.
While this error was exposed by #377 the mismatched tag was likely added in https://github.com/line/promgen/commit/4e98e9be5ced058567ad9dab4f4f2be5adfedf7a#diff-c741593aed98e419f1a6817df3e761a2eaf49e9421945b42cd0632d2c34e8ce9
when we moved some of the templates around
cc @KarboniteKream
> [BUGFIX] Fix missing closing div tag which triggered VueJS error

- promgen/tests/test_host_add.py
- promgen/validators.py
One more attempt to fix the edge cases for validating hostnames. We want to allow bare hostnames and fqdn, but not allow any other special characters like an accidental port or path part
References #383 #380
> [BUGFIX] Update validator to allow hostname only entries

- promgen/context_processors.py
- promgen/settings.py
- promgen/templates/promgen/help_menu.inc.html
- promgen/templates/promgen/navbar.html
Replace our EXTERNAL_LINKS settings with a template override to allow more flexibility in customizing the menu option and how things are displayed.
> [IMPROVEMENT] Support help_menu.inc.html override

- promgen/models.py
When overwriting site rules, a copy of the original rule is created. If a user
does that, it's because they prefer the copy (with their modifications) than the
original. Because of that it makes sense to enable the copy by default.
> Enable copied rules by default

- promgen/signals.py
- promgen/views.py
When using get_or_create, we want to ensure an owner, but we do not care
if someone else has ownership. Move our owner field to defaults to avoid a
duplicate sender in some cases.
> [BUGFIX] Fix for duplicate user subscribe

- promgen/templates/promgen/farm_detail.html
- promgen/templates/promgen/host_form.html
A few updates from 1f821f1370f90248076e1f2ac8c903f014f46472 were missing the template load tag
> [BUGFIX] Fix missing `load i18n` tag

- promgen/signals.py
When calling post_save with Service, we call out to save_project, but
did not handle some of our required parameters correctly
- Change functions to all kwargs to hopefully catch errors in the future
- Default raw=False in our wrapper to match post_save.send
> [BUGFIX] Fix handling of kwargs in skip_raw decorator

- promgen/templates/promgen/home.html
Before, when the Home page was empty it just included a small text linking to
the services and data sources.
Now it has a more friendly headline, a bigger font to improve readability, and a
new link for directly creating a service. This new link will save the user from
having to navigate to the "Services" page in order to create its first service.
> Refresh the Home page when it's empty

- promgen/templates/promgen/rule_detail.html
Before, when you wanted to see the description of a rule, you needed to edit it in order to load the form and then look at the description field. That was a little bit weird and could be considered as an anti pattern for good usability.
Now, since we have added the description to the `rule_dict` template tag, it is displayed in the rule detail page.
> Show rule description in rule page

- promgen/templates/promgen/shard_list.html
- promgen/views.py
The view was looping through the Shard objects using "project_set.count" as the argument for "dictsortreversed". This was causing an empty loop because "project_set.count" is not an attribute in the Shard objects.
"project_set" is a backwards relationship [1] created by Django, and "count" is a function that returns the number of objects in that relationship.
The reason why "project_set.count" was used in the view was to display the shards sorted by the number of projects, so the shards with most projects appear at the top, and the ones with less projects appear at the bottom.
To fix the issue we just create a "num_projects" annotation in the query that retrieves the shards, and use it as the argument for "dictsortreversed".
1: https://docs.djangoproject.com/en/dev/topics/db/queries/#backw …
> Fix DatasourceList view

- promgen/tests/test_alert_rules.py
- promgen/tests/test_cli.py
Previously we had several tests that used the Django ORM to populate data. Using fixtures should give us more reproducible test.
> [INTERNAL] Migrate more tests to use fixtures

- promgen/templates/promgen/ajax_clause_check.html
- promgen/views.py
A common source of confusion when writing Rules, is the global namespace of Prometheus when on a shared server. It's very easy to write a rule that covers more projects than expected.
To help avoid this, we want to upgrade the rule test button to check the labels that are returned vs the expected labels.
This was code that was written months ago, but got delayed due to other infra tasks. It could probably be made more robust, but I think we're ultimately going to take a deeper look at the rules system in the near future.
> [IMPROVEMENT] Rule Test should check for unrelated labels

- promgen/templates/base.html
To make it easier to distinguish testing environment from a live one, we want to add an obvious warning alert at the top of the screen.
> Add debug warning to top of page

- docker/requirements.in
- docker/requirements.txt
While updating the Python version in #429, our redis requirement was accidentally removed. We want to ensure the default container version can use redis.
> [BUGFIX] Fix missing celery redis

- promgen/templates/promgen/alert_list.html
- promgen/views.py
To help with debugging, it's useful to have a filter for both errors and other alerts that did not send. We also want to better highlight a date change to help with debugging.
> [IMPROVEMENT] Additional alert filters

- promgen/errors.py
- promgen/forms.py
- promgen/prometheus.py
- promgen/proxy.py
- promgen/tests/test_silence.py
Until we have a more robust permission system, we need to be cautious and ensure that users can not accidentally set a global level silence. To do this, we will check to see if the pending silence has alertname as a matcher, and if so, enforce that it also includes a service or project label.
> [BUGFIX] Stricter checks about silencing global rules

- promgen/views.py
In f48218e3228ab625362c66811c11597381f0a872 we refactored how rules stored labels/annotations but when we updated this prefetch entry we accidentally changed it so that is no longer a proper tuple. This needs to be a tuple so that it does not try to treat each character as an entry.
> [BUGFIX] Fix for rule prefetch on /search

- promgen/views.py
In 1454ed0466125a56dc2459617727d87950eb90af we migrated to JsonField for label and annotation storage, but one instance of add_label was missed.
> [BUGFIX] Fix instance of Rule.add_label

- Makefile
- promgen/prometheus.py
- promgen/tests/test_alert_rules.py
- promgen/views.py
We need to ensure that our labels and annotations are also evaluated in the correct order when we call promtool to validate our rules.
> [BUGFIX] Fix check for invalid annotation name

- .github/workflows/sphinx.yml
- .gitignore
- Dockerfile
- docker/requirements.txt
- promgen/__init__.py
- promgen/management/commands/bootstrap.py
- promgen/settings.py
- setup.cfg
Since we have django-environ and we have been moving to a docker deployment, it doesn't make sense to keep envdir around anymore. This PR cleans up the initial bits, though we'll also have a future PR to cleanup the `promgen bootstrap` command more.
> [INTERNAL] Remove envdir

- promgen/static/js/mixins.vue.js
- promgen/static/js/promgen.vue.js
- promgen/templates/base.html
- promgen/templates/promgen/alert_row.html
- promgen/templates/promgen/silence_row.html
- promgen/templates/promgen/vue/promql_query.html
In Vue 3, filters are removed and no longer supported. Instead, they recommend replacing them with method calls or computed properties.
https://v3-migration.vuejs.org/breaking-changes/filters.html
Since those methods can be reused in multiple components we store them as mixins instead of defining them in specific components. Mixins work in both Vue 2 and Vue 3.
The recommendation for migrating global filters in Vue 3 is to store them as global properties [1], however that is not supported in Vue 2.
1: https://vuejs.org/api/application.html#app-config-globalproperties
---
This PR will make the future PR for migrating to Vue 3 much shorter.
> Convert Vue filters into methods

- .github/workflows/sphinx.yml
Closes #443 
- deploy with action artifacts, not from gh-pages branch
- check ref with master, not with main
ex) https://github.com/sh-cho/promgen/actions/runs/6706997395
Only deploy on push master branch (using [github actions context](https://docs.github.com/en/actions/learn-github-actions/contexts#determining-when-to-use-contexts))
`gh-pages` branch can be removed after this PR is merged
> Fix github pages deploy

- .github/workflows/django.yml
- .github/workflows/docker.yml
- .github/workflows/sphinx.yml
We can set a concurrency setting for each of our actions so that pushing to a branch cancels in-progress runs without conflicting with runs on other branches
https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
> Configure concurrency setting for actions

- .readthedocs.yml
- promgen/templates/promgen/help_menu.inc.html
In #444 the github actions was fixed to publish to gh-pages properly. Since our readthedocs build is current broken anyways, it is probably better to promote the github pages version as canotical since that will also result in less of a maintenance burden for other contributors.
> Remove readthedocs in favor of Github actions and gh-pages

- .github/workflows/sphinx.yml
> WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
> (in sphinx workflow log)
(https://line.github.io/promgen/user/terms.html)
Dot graph is not displayed because graphviz package is not installed in workflow.
After install graphviz package, graph is rendered well (https://sh-cho.github.io/promgen/user/terms.html)
> Install graphviz package in sphinx workflow

- docs/user/terms.rst
Some of these terms have not been updated in a while and need to be updated to show the current relationship between them.
> [DOCUMENTATION] Update terms in documentation

- .github/workflows/django.yml
- .github/workflows/docker.yml
- .github/workflows/sphinx.yml
Collecting dependabot updates into a single PR.
Looking at some tags as an example
https://github.com/actions/setup-python/tags
We have to pin more exact versions since there's not really a concept of semver for tags
> Dependabot

- README.md
Value of case is **docker-compose-boostrap** not **boostrap**
https://github.com/line/promgen/blob/master/docker/docker-entrypoint.sh#L10
> Fix Promgen init documentation

- promgen/notification/webhook.py
In the same way that is done for the other notifiers, we have added an alias field to prevent secret tokens to be leaked when displaying the notifier's description in the UI.
> notification/webhook: Add alias field

- promgen/models.py
We have noticed that deleting projects that contain rules throw an error than can be seen on user's side as an "Internal Error!" page.
This occurs because the rule's "content_object.name" is trying to be accessed after the project has been deleted, therefore "content_object" is None and does not contain a "name" member.
> models.py: Rule: Check content_object before accessing it

- promgen/static/js/promgen.vue.js
Before creating the silence, the silence form appears and we have the possibility to remove any labels that were added by default. When doing so, an error like this one happens:
TypeError: this.$delete is not a function
The error occurs because the "$delete" instance method [1] has been removed in Vue 3 [2], but we forgot to adapt this part of the code when we did the migration.
1: https://v2.vuejs.org/v2/api/#vm-delete
2: https://v3-migration.vuejs.org/breaking-changes/#removed-apis
> promgen.vue.js: Fix silence form's delete label

- promgen/views.py
Before, when displaying the audit logs for services, there was no information regarding when a project was added on a service, or modified, or deleted.
That information is useful when tracking things down while debugging, so let's add it.
> Audit logs: Show projects for services

- promgen/tests/test_models.py
- promgen/validators.py
Previously some of our regex checks were not properly bounded. By adding ^ and $ to our regex, we can ensure the entire string gets checked.
> [BUGFIX] Stricter validation

- promgen/prometheus.py
- promgen/proxy.py
- promgen/static/js/promgen.vue.js
- promgen/tests/__init__.py
- promgen/tests/examples/silence.duration.json
- promgen/tests/examples/silence.range.json
- promgen/tests/test_silence.py
For most things, changing v1 to v2 works.
The silence API now expects startsAt for all requests, so we make that adjustment.
The Alerts and Silences API now return directly instead of a data field so we also make that adjustment.
Also do some minor adjustments to use HTTPStatus instead of hardcoded status codes.
> [IMPROVEMENT] Update to Alertmanager v2 API

- promgen/static/js/promgen.js
As we work towards removing our dependence on jQuery, we want to rewrite our copyto helper in plain javascript
> [IMPROVEMENT] Rewrite copyto in plain javascript

- promgen/static/js/promgen.js
Javascript doesn't have a default debounce function, so we borrow one from a blog post. If we don't use a debounce function then our event listener on 'input' runs too frequently and makes the page feel slow.
> [IMPROVEMENT] Rewrite filter from jQuery to regular JavaScript

- promgen/notification/user.py
- promgen/signals.py
- promgen/tasks.py
- promgen/tests/notification/test_user_email.py
Previously when checking the extra values, we never passed along our enabled query, so that child notifiers would always trigger even if they were disabled.
> [BUGFIX] Fix notification splay

- docker/requirements.txt
- promgen/management/commands/bootstrap.py
- promgen/settings.py
- promgen/templatetags/promgen.py
- promgen/tests/test_alert_rules.py
- promgen/tests/test_signals.py
- promgen/urls.py
- promgen/views.py
- pyproject.toml
Django 3.2 is past EOL ( https://endoflife.date/django ) and 4.2 is the current LTS version. There are not many changes that seem to directly affect us, and we can simply run the third-party django-upgrade command to take care of a few minor updates.
> Upgrade to Django 4.2

- promgen/views.py
self.object will be configured in form_invalid, so we can remove it from the top. We want to ensure that self.object is clean when we have to re-render the page on failed submission, so we move it to form_invalid
> [BUGFIX] Reset self.object on form_invalid

- promgen/forms.py
- promgen/models.py
Some of the behavior changed between Django 3.2 and 4.2 so we make a fix here to get around it. Also add the rule pk to the __str__ for us to use while debugging
> [BUGFIX] Fix for foreign key check regarding m2m

- promgen/settings.py
- promgen/templates/django/forms/widgets/textarea.html
- promgen/templates/promgen/project_detail_configuration.html
- promgen/templates/promgen/rule_detail.html
- promgen/templates/promgen/service_block.html
We want to add v-pre automatically to all text area tags, since those are often used for general user descriptions.
We also add v-pre tags for other areas where an objects .description tag might be rendered.
> [BUGFIX] Use additional v-pre tags to avoid issues with user input.

- promgen/templates/promgen/global_messages.html
It seems that v-pre was being ignored, so let's place it closer to the stuff we want to ignore.
> global_messages: Move v-pre to a more specific place

- promgen/views.py
Despite of having added v-pre in the right place, for some reason it looks like that template is not being updated properly when re-running the Django app.
Until we find a fix for that issue we are adding a simple ugly escape for square brackets to tackle the XSS problem.
> views/NotifierUpdate: Escape square brackets in global message

- promgen/templates/promgen/project_row.html
- promgen/templates/promgen/rule_block.html
- promgen/templates/promgen/search.html
By putting v-pre in parent elements in order to avoid putting more v-pre elements on some of its children, we have broken the search results.
Let's avoid doing this and instance put v-pre on the elements that need them.
> Fix search: Be more specific with v-pre

- promgen/views.py
When creating a new Rule and testing its query before saving it, an error like this was happening:
'Rule' instance needs to have a primary key value before this relationship can
be used.
From the user's perspective, the test was not happening and the server returned a 500 error.
When testing a new Rule that has not been saved, a temporary Rule object is created in memory. Since that object is not saved, it does not contain a primary key.
Due to some changes introduced in Django 4, errors are thrown if that object without a primary key is used. To fix that issue, we manually assign a primary key.
> Fix testing Rule query before saving

- promgen/prometheus.py
- promgen/templatetags/promgen.py
In #495 ( 06a2c20c2a09dfd284d1cb16a4786eedb85e99fb ) we upgraded Django. This means that Django itself doesn't depend on pytz, but we still had a few instances of our code requiring it. Instead of making pytz a dependency of Promgen, we can refactor a few bits to remove the dependency.
> Django fixes

- docker/requirements.txt
- pyproject.toml
Though the upgraded list of dependencies required by celery are unfortunate, it's better to upgrade to a newer version for security reasons. Since we're not doing anything particularly fancy with Celery, it doesn't look like any code changes are required
> Upgrade Celery

- promgen/static/js/promgen.vue.js
- promgen/templates/promgen/vue/promql_query.html
This component had some issues that prevented it to render properly.
First, the unnecessary usage of 'this_ = this'. In a Vue component, 'this' always refers to the component itself.
Second, the unreliable way to change the display CSS property by accessing 'this_.$el.style.display'. In Vue, we can do conditional rendering using the v-show directive. We have defined a new 'ready' variable that becomes 'true' when the component is ready to be rendered, and use v-show to toggle the visibility of the component based on the value of that variable.
Third, the position of the '<slot></slot>' in the template. This slot is meant to allow the user to describe the result of the query. For instance, if the result of the query is the number of samples, a good content of that slot would be the string …
> Fix promql-query Vue component

- promgen/views.py
When using the 'test' button for an exporter, we previously *only* checked the status code and assumed things were good. It is very possible for an incorrect endpoint to be registered, so we should ensure that the registered endpoint produces correct Prometheus metrics.
Right now, we will return a somewhat *developer* like output, but I expect to make the output more user friendly as we cleanup some of our internal test URLs.
> [IMPROVEMENT] Test metrics validity when testing Exporter

- promgen/proxy.py
- promgen/util.py
- promgen/views.py
We can move our proxy_error wrapper so that it can be reused in our PromqlQuery View to keep things consistent.
> [INTERNAL] Move proxy_error to util.proxy_error for reuse

- promgen/fixtures/testcases.yaml
- promgen/rest.py
- promgen/templates/promgen/navbar.html
- promgen/tests/examples/export.rule.yml
- promgen/tests/examples/export.targets.json
- promgen/tests/test_cli.py
- promgen/tests/test_renderers.py
- promgen/tests/test_routes.py
In the future, I would like to improve the way we handle some of the rendering, so the first step is to ensure we have some proper test cases to check for when rendering changes.
Most of this is updates for test cases, but also add a minor new route as part of a future cleanup of the public api routes.
> Renderer tests

- promgen/fixtures/testcases.yaml
- promgen/rest.py
- promgen/templates/promgen/navbar.html
- promgen/tests/examples/export.urls.json
- promgen/tests/test_renderers.py
Similar to our previous PR, we want to add some starting test cases to our url rendering paths so that we are prepared for future updates.
> Add test for URL rendering

- promgen/static/css/promgen.css
- promgen/static/js/promgen.vue.js
- promgen/templates/base.html
- promgen/templates/promgen/navbar.html
- promgen/templates/promgen/vue/silence_create_modal.html
- promgen/templates/promgen/vue/silence_list_modal.html
1. Change the current list interface to a modal design.
2. Within the modal, Provide table about Silence list
3. Introduce filter feature within the modal interface.
> Implement "Silence List" Feature as a Modal

- promgen/locale/ja/LC_MESSAGES/django.po
- promgen/static/css/promgen.css
- promgen/templates/promgen/service_action_button_group.html
- promgen/templates/promgen/service_block.html
Split this [PR](https://github.com/line/promgen/pull/520) into two parts.
This one is the part1, only focus on `service-button-group` changes
Before:
After:
> Organize Service View Page with Tabs(part1)-Service button group

- promgen/static/css/promgen.css
- promgen/templates/promgen/vue/silence_create_modal.html
- promgen/templates/promgen/vue/silence_list_modal.html
- promgen/templates/promgen/vue/silence_row.html
> [IMPROVEMENT] Truncate long silence matchers

- promgen/templates/promgen/service_block.html
- promgen/templates/promgen/service_block_panel_notifiers.inc.html
- promgen/templates/promgen/service_block_panel_rules.inc.html
- promgen/templates/promgen/service_detail.html
- promgen/templates/promgen/service_detail_projects.html
- promgen/templates/promgen/service_detail_projects_table.html
Categorizing the service view page into tabs aims to provide consistency and improve the readability of the page.
Before:
After:
> Organize Service View Page with Tabs(part2)

- promgen/filters.py
- promgen/rest.py
- promgen/serializers.py
- promgen/tests/examples/rest.farm.1.json
- promgen/tests/examples/rest.farm.json
- promgen/tests/test_rest.py
- promgen/urls.py
Adding 2 APIs for retrieving Farm's data:
1. `GET /rest/farm`
Returns a JSON array of all farms in Promgen. 
_Available request params:_
- **source**: string. The returned array of farms will be of this source type. **Exact match**.
- **name**: string. The returned array of farms will have the name which contains the parameter's value. **Contains**
_Sample response:_
```
[
{
"id": 1,
"url": "http://127.0.0.1:8000/farm/1",
"name": "farm-test",
"source": "promgen"
},
...
]
```
2. `GET /rest/farm/:id`
Returns the farm matching the ID as a JSON object, including the list of hosts.
_Sample response:_
```
{
"id": 1,
"url": "http://127.0.0.1:8000/farm/1",
"name": "farm-test",
"source": "promgen",
"hosts": [
{
"url": "http://127.0.0.1:8000/host/host-test.com",
"name": "host-test.com"
},
...
]
} …
```
> Implement retrieval "Farm" APIs

- promgen/models.py
- promgen/tests/test_models.py
When creating or updating a rule on Promgen, the corresponding rule data on Prometheus will be given an annotation **"rule"** that is the link to that rule on Promgen. However, the annotation rule on Promgen always has the URI **"/rule/0"** because it has not been intentionally set up:
- Previously, the value of **annotation["rule"]** on Promgen was accidentally set when loading data from the [AlertRuleForm](https://github.com/line/promgen/blob/master/promgen/forms.py#L137C7-L137C20). Specifically, in the form's [clean()](https://github.com/line/promgen/blob/master/promgen/forms.py#L151) method, there is a declaration of [prometheus.check_rule()](https://github.com/line/promgen/blob/master/promgen/forms.py#L170C2-L170C39), which includes a …
> Custom the save method of the Rule model to handle the annotation "rule"

- promgen/views.py
If an object is **deleted**, the current code cannot find the object or its related objects, and causes an error in the Audit Log feature (Edit History) when we try to filter that object. In that case, we directly use the **object_id** and **content_type_id** fields of the **Audit model** to find it and skip finding the related objects.
**AS-IS:** 
**TO-BE:**
> Handle query for the audit logs of deleted objects

- promgen/templates/promgen/service_detail.html
This was removed when we changed the service detail page to use tabs. This commit brings it back.
> [FIX] templates/service_detail: Show description

- promgen/static/js/promgen.vue.js
- promgen/templates/promgen/vue/silence_list_modal.html
BEFORE:
AFTER:
BEFORE:
AFTER:
BEFORE:
AFTER:
BEFORE:
AFTER:
> Improve UI/UX of the global list of silence

- promgen/serializers.py
Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since Django REST Framework 3.3.0, and is now disallowed. It caused an internal error when calling the notifiers retrieve API. We add an explicit fields = '__all__' to the SenderSerializer serializer to resolve this issue.
> [BUGFIX] Error when retrieve notifiers from a service or project

- promgen/serializers.py
For security reason, we should not return token data of to users through the retrieve Shard API.
BEFORE:
AFTER:
> Remove 'authorization' field from the retrieve Shard API

- promgen/fixtures/testcases.yaml
- promgen/serializers.py
- promgen/tests/examples/rest.farm.1.json
- promgen/tests/examples/rest.farm.json
Field 'owner' was added to the Farm model in commit 2dd4338. The owner's name should be returned through the Farm retrieve APIs, instead of the owner's primary key. This was overlooked on a previous pull request. (https://github.com/line/promgen/pull/582)
AS-IS:
TO-BE:
> Make the Farm retrieve APIs return the name of the Farm's owner

- .github/workflows/django.yml
- .github/workflows/docker.yml
- .github/workflows/sphinx.yml
Ubuntu 20.04 has been retired and our actions are failing with the following error message:
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be
removed on 2025-04-15. For more details, see
https://github.com/actions/runner-images/issues/11101
GitHub Actions has encountered an internal error when running your job.
> GitHub Actions: Update Ubuntu runner to 24.04

- promgen/templates/promgen/farm_detail.html
- promgen/templates/promgen/farm_duplicate.html
- promgen/templates/promgen/farm_form.html
- promgen/templates/promgen/host_404.html
- promgen/templates/promgen/host_detail.html
- promgen/templates/promgen/host_form.html
- promgen/templates/promgen/host_list.html
- promgen/templates/promgen/import_form.html
- promgen/templates/promgen/link_farm.html
- promgen/templates/promgen/rule_import.html
- promgen/templates/promgen/rule_list.html
- promgen/templates/promgen/search.html
- promgen/templates/promgen/url_form.html
- promgen/templatetags/promgen.py
On some pages of Promgen, the Home link in the breadcrumb is redirected to the Services page instead of the Home page. We have fixed all these errors by using the "breadcrumb" template tag. We also made some improvements to this template tag to handle the Farm object and add the "v-pre" tag by default.
> [BUGFIX] "Home" link in the breadcrumb redirects to the "Services" page

- promgen/views.py
Sometimes, when users want to search for a keyword, it may accidentally include leading or trailing spaces because the user copied the keyword from elsewhere or due to a typing error. This results in empty search results because nothing matches the input. Therefore, before starting the search, we clean up the user's input by trimming the spaces at the beginning and at the end of the input string.
> Trim whitespaces of search input

- promgen/rest.py
Django's View class is designed for building traditional web applications that render HTML templates. On the other hand, APIView is part of Django REST Framework and is specifically designed for building robust RESTful APIs. Therefore, we have transitioned from using Django's View class to Django REST Framework's APIView for the AlertReceiver API. This change allows us to implement advanced features such as authentication and permissions in the future.
This update does not affect the current behavior of the AlertReceiver API.
> Use DRF's APIView for AlertReceiver API

- promgen/templates/promgen/project_detail_configuration.html
- promgen/templates/promgen/rule_detail.html
- promgen/templates/promgen/rule_update.html
- promgen/templates/promgen/service_action_button_group.html
There are some buttons that represent actions, but the button names are displayed as nouns. This can be ambiguous for users. For example, a button that allows users to view the edit history of an object is named "Edit History," but at first glance, users might misunderstand it as a button related to editing some historical information. This is especially true when the button is placed in a group of "Actions" buttons alongside other buttons that indicate actions, such as "Export", "Subscribe" and "Delete."
Therefore, we have changed the names of some buttons to clarify their meanings.
- Edit History -> View Edit History
- Alert History -> View Alert History
AS-IS:
TO-BE:
> Rename some buttons

- promgen/templates/base.html
We added a version number as a query string to the promgen.vue.js file URL to prevent the user's browser from caching it. In the future, this version number will be manually increased when we modify the promgen.vue.js file. This ensures that users always receive the latest version of the JavaScript file every time we change it.
> Preventing the browser from caching promgen.vue.js file

- promgen/views.py
Promgen's Farm system is a pluggable system that allows people to write their own plugins. The default plugin is what allows creating local farms, also known as "promgen" farms, and is shipped with Promgen. But other plugins can be added to discover external farms, and link them to projects. After linking them to a project, if that external farm was not already in Promgen's data base, it will be added.
This commit ensures that when such external farms are added to the data base they have an owner set.
Those external farms are not editable, so the owner fields won't be used to decide who can modify the farm. However, since we are planning to enforce the owner fields to not be null, we need to ensure the owner field is set.
> Set owner when adding external farms

- promgen/templates/django/forms/table.html
The extra white space between the label and the form field is not normal. We fixed it by overriding the Django's template form/table.html then styling the <th> tag. This solution ensures that the change only affects UIs that use the function form.as_table.
ref: https://github.com/django/django/blob/stable/4.2.x/django/forms/templates/django/forms/table.html
> Align the form field with its label

- promgen/templates/promgen/service_form.html
Add the missing service links in the breadcrumb of the Service Update page.
AS-IS:
TO-BE:
> Fix the breadcrumb of the Service Update page

- promgen/templates/promgen/project_form.html
We are using the same form for registering and updating a project. Therefore, there is an empty row at the end of the form when registering a new project because that row is only for updating the service of the project. As a result, we have hidden this row when registering a new project.
AS-IS:
TO-BE:
> Fix empty row when registering a new project

- promgen/templates/promgen/sender_row.html
Currently, when displaying the notifier list, the Actions column will not be shown if show_edit is false. However, the filter column is still displayed along with the Add and Remove buttons when show_edit is false. For instance, when we display the Service notifiers from the Project detail page, the Action column is hidden by using the show_edit variable. However, even if the Actions column is hidden because the users are not supposed to edit those notifiers, they are still able to add filters to it, which is an edit action on the notifier.
We have changed it to only display the filters as labels and not show any actionable buttons so that the users are not supposed to add, edit or remove filters of a notifier if the value of 'show_edit' is false.
AS-IS:
TO-BE:
> Make notifier's filters not editable if 'show_edit' is false

- promgen/templates/promgen/project_detail.html
Previously, we displayed the Active Silence list of a Service using a modal dialog. Now, the way we display the Active Silence list of a Project will also be done similarly, changing from displaying as a collapsible table to a modal dialog to unify the user experience.
> Using only one UI for showing Active Silences

- promgen/settings.py
We fixed a bug that AUTHENTICATION_BACKENDS setting from PROMGEN was not replaced Django settings. Loading overrides from PROMGEN to replace Django settings should always be at the end of the settings.py file. Therefore, we changed the location of the AUTHENTICATION_BACKENDS setting.
> Fix the bug that overrides AUTHENTICATION_BACKENDS not work

- promgen/templates/promgen/permission_row.html
Currently, the only way to change a member's role is to delete the member and add them again with the desired role. From a UX perspective, this is somewhat inconvenient. Therefore, we have added a small button next to each member's role label in the member list table to quickly support changing the member's role.
And since users cannot remove the owner's permission without transferring
ownership, we also have removed the button for this action from the UI.
> Support change member's role on UI

- promgen/templates/promgen/farm_detail.html
At commit 8b90ea69, we added a confirmation message when users delete a local farm from the "Hosts" tab on the Project Detail page to emphasize the irreversibility of this action. We have updated this message for the same action on the Farm Detail page.
> Update the confirmation message for farm deletion on Farm Detail page

- promgen/serializers.py
After removing "farm" field from the Project model, calling the Project Retrieve API will cause an AssertionError. This happened because the serializer cannot find the "farm" field which was declared in the excluded field list. We have removed the "farm" field from the excluded field list of ProjectSerializer to resolve this bug.
> Remove excluded "farm" field from ProjectSerializer
