line/promgen

- lib/promgen/alert/sender/ikachan.rb
I think it is better than yellow :)
> Set the color of ikachan resolved message to green

- views/register_rule.erb
> Additional examples for Rules page

- lib/promgen/alert/sender/ikachan.rb
- lib/promgen/alert/sender/mail.rb
- test/promgen/test_alert.rb
> Add additional information to Email and Ikachan alerts

- lib/promgen/web/route/host_route.rb
- lib/promgen/web/route/project_exporter_route.rb
- lib/promgen/web/route/project_route.rb
- views/add_host.erb
- views/register_project_exporter.erb
- views/show_rule.erb
- views/update_project.erb
Same pull request but against develop
Home
Home > Service
Home > Service > Project
Home > Service > Project > etc
> Fix the breadcrumbs to show the full hierarchy

- lib/promgen/rule_writer.rb
- migrations/13_rule_text_length.rb
- views/register_rule.erb
- views/update_rule.erb
> Use textarea for rule update page to make things more readable by avoiding side scrolling

- .dockerignore
- .gitignore
- README.md
- docker-compose.yml
- docker/prometheus.yml
This should accomplish most of the same thing as @Tommassino 's request in #43 but with better inline documentation
> Update example docker/prometheus.yml with additional documentation

- promgen/notification/slack.py
- promgen/tests/notifications/slack.body.txt
- promgen/tests/notifications/slack.resolved.txt
- promgen/tests/test_slack.py
Complements #40 by adding a test case.
> Test Case for Slack Sender

- Dockerfile
> Update PROMGEN_CONFIG_DIR in Dockerfile

- promgen/static/css/promgen.css
- promgen/templates/promgen/link_farm.html
- promgen/templates/promgen/project_detail.html
- promgen/templates/promgen/rule_update.html
- promgen/templates/promgen/service_detail.html
- promgen/templates/promgen/shard_detail.html
- promgen/templates/promgen/shard_list.html
- Update headers on some of the _detail pages to be a bit more
consistent across pages
- Use CSS Grid to have more control over how items are wrapped
> Update some page headers and use css grid

- README.md
> Remove duplicated content from README.md and direct to CONTRIBUTING.md

- promgen/notification/webhook.py
- promgen/tests/test_webhook.py
Ensure we pass our dictionary as json to requests
> Fix webhook to POST json data as intended

- .circleci/config.yml
- Makefile
* Cleanup Makefile to handle our most common operations
* Fix circleci config to ignore gh-pages repo
> Fix Makefile and circleci configuration

- promgen/templates/promgen/shard_detail.html
- promgen/templates/promgen/shard_list.html
> Re-add link to shard

- promgen/templates/promgen/exporter_form.html
> Add help text describing job label usage

- README.md
> invalid Database example

- promgen/templates/promgen/home.html
- promgen/templates/promgen/status.html
- promgen/urls.py
- promgen/views.py
- Home page shows only the services that you are subscribed to
- TODO: Handle empty set
> Update homepage to show only subscribed projects

- Pipfile.lock
- promgen/rest.py
- promgen/serializers.py
- promgen/settings.py
- promgen/templates/base.html
- promgen/templates/promgen/navbar.html
- promgen/templates/promgen/project_detail_configuration.html
- promgen/templates/promgen/service_block.html
- promgen/templates/rest_framework/api.html
- promgen/urls.py
- promgen/views.py
- setup.py
* Support for reading from shards, services, projects
> [ENHANCEMENT] Initial read-only API provided by django-rest-framework

- promgen/tasks.py
- promgen/tests/examples/heartbeat.json
- promgen/tests/examples/promgen.yml
- promgen/tests/test_api.py
- promgen/tests/test_webhook.py
- promgen/views.py
* Support an 'alert_blacklist' setting for filtering out heartbeats or
other debug style alerts
> [ENHANCEMENT] Support filtering out alerts

- promgen/settings.py
- promgen/urls.py
- promgen/wsgi.py
Fix #117 
This should fix the errors due to upgrading WhiteNoiseMiddleware
> Fix for serving /static/ from docker container

- promgen/static/js/promgen.vue.js
- promgen/templates/promgen/alert_row.html
Allow silencing a specific alert
> Add button to silence a single alert

- promgen/forms.py
- promgen/migrations/0001_squashed_0044_common-rules.py
- promgen/models.py
- promgen/proxy.py
- promgen/static/js/promgen.vue.js
- promgen/templates/promgen/global_messages.html
- promgen/validators.py
Refactoring to fix our silence duration validation and show errors as an alert
> [BUGFIX] Fix validation of silence duration

- promgen/models.py
- promgen/notification/user.py
- promgen/prometheus.py
- promgen/rest.py
- promgen/signals.py
- promgen/tasks.py
- promgen/tests/test_email.py
- promgen/tests/test_ikasan.py
- promgen/tests/test_linenotify.py
- promgen/tests/test_rules.py
- promgen/tests/test_slack.py
- promgen/tests/test_user_email.py
- promgen/tests/test_webhook.py
- promgen/views.py
* Instead of using a non-standard abstract class to handle our lookups,
create a Manager that we can use when filtering on objects
> [INTERNAL] Refactor manager class and validators

- promgen/static/js/promgen.vue.js
I want to show what the status of silence is pending.
So we can see silence list without expired
> Fix filterActiveSilences condition

- promgen/models.py
> [BUGFIX] Fix arguments for create/filter/get_or_create

- promgen/proxy.py
- Refactor our concurrent.futures code into a parent class + generator
- Add proxy_error method to convert requests error into HttpResponse
> [INTERNAL] Refactor how we proxy errors

- promgen/models.py
- promgen/prometheus.py
- promgen/templates/promgen/host_block.html
- promgen/templates/promgen/rule_block.html
- promgen/templates/promgen/rule_detail.html
- promgen/templates/promgen/rule_form_block.html
- promgen/templates/promgen/rule_update.html
- promgen/templates/promgen/search.html
- promgen/templatetags/promgen.py
- promgen/tests/notifications/email.body.txt
- promgen/tests/notifications/ikasan.body.txt
- promgen/tests/notifications/linenotify.body.txt
- promgen/tests/notifications/slack.body.txt
- promgen/tests/test_rules.py
- promgen/urls.py
- promgen/views.py
> [IMPROVEMENT] Read-only rule page

- promgen/models.py
- promgen/templates/promgen/rule_update.html
- promgen/tests/test_rules.py
- Fix rule update form to properly post to 'rule-edit'
- Fix rule renderer to link to 'rule-detail'
> [BUGFIX] Fix HTTP 405 when updating a rule

- promgen/context_processors.py
- promgen/notification/__init__.py
- promgen/prometheus.py
- promgen/proxy.py
- promgen/tasks.py
- promgen/templatetags/promgen.py
- promgen/tests/examples/promgen.yml
- promgen/util.py
- Add promgen.util.setting to read settings
- Move config_writer:path -> prometheus:targets
- Move alert_blacklist -> alertmanager:blacklist
> [IMPROVEMENT] Settings helper for Promgen config

- promgen/views.py
Be more explicit about catching the specific exceptions to better report the correct error to the end user
> [BUGFIX] Catch ConnectionError and RequestException for better results

- Pipfile.lock
- docker/requirements.txt
- setup.py
See https://github.com/celery/kombu/issues/1063
> [BUGFIX] Pin kombu to 4.6.3 to fix bug with redis exchange

- promgen/forms.py
- promgen/mixins.py
- promgen/tests/test_routes.py
- promgen/urls.py
- promgen/views.py
- Rename AlertRuleRegister to distinguish our future RecordingRule
- Refactor AlertRuleRegister to split up form_valid from form_import
> [INTERNAL] Refactor AlertRuleForm and AlertRuleRegister for future work

- promgen/prometheus.py
- promgen/renderers.py
- promgen/rest.py
- promgen/templates/promgen/project_detail_configuration.html
- promgen/templates/promgen/service_block.html
- Move some of our `register` options under a dropdown menu
- Minor refactoring of our common rest action decorators
> [INTERNAL] Minor UI and API refactoring

- promgen/templates/registration/login.html
Social auth login should pass the next parameter to properly redirect
> [BUGFIX] Fix login redirect with social auth

- promgen/templates/promgen/notifier_block.html
- promgen/templates/promgen/sender_row.html
> Add scroll bar to notifier table

- CODE_OF_CONDUCT.md
- README.md
- promgen/templates/promgen/rule_form_block.html
- setup.cfg
> Use Github pages for canonical documentation

- promgen/models.py
- promgen/templates/promgen/home.html
- promgen/templates/promgen/navbar.html
- promgen/templates/promgen/profile.html
- promgen/templates/promgen/project_detail_configuration.html
- promgen/templates/promgen/project_form.html
- promgen/templates/promgen/service_block_projects.html
- promgen/templates/promgen/shard_detail.html
- promgen/templates/promgen/shard_list.html
- promgen/templatetags/promgen.py
- promgen/urls.py
- promgen/views.py
To avoid some confusion in the UI and to better aline some terms. This PR *only* changes the user visible parts. Future PRs will clean up additional places
> Rename "Shard" to "Datasource" for more descriptive name

- promgen/notification/user.py
> User notifier should only return enabled senders

- promgen/notification/__init__.py
- promgen/notification/slack.py
- promgen/tasks.py
- promgen/tests/notification/test_email.py
- promgen/tests/notification/test_linenotify.py
- promgen/tests/notification/test_slack.py
- promgen/tests/notification/test_user_email.py
- promgen/tests/notification/test_webhook.py
- promgen/util.py
- Be more explicit about handling defaults for NotificationBase.config and util.setting
- Check AlertError in our unit test results
- Split send_alert into send_notification to better handle our counting logic
> Notification handling improvements

- docker/requirements.txt
> Whitenoise upgrade

- Makefile
- setup.cfg
Fix version mismatch between setup.cfg and requirements.txt
> [INTERNAL] Fix version mismatch

- Dockerfile
- Makefile
COPY the needed files from the upstream container to simplify our build a bit
> Copy promtool bin from upstream docker container

- Makefile
- docker/requirements.txt
- setup.cfg
Update django and a few other packages
> [INTERNAL] Django version update

- promgen/fixtures/extras.yaml
- promgen/fixtures/testcases.yaml
- promgen/settings.py
- promgen/signals.py
- promgen/tests/__init__.py
- promgen/tests/examples/silence.duration.json
- promgen/tests/examples/silence.range.json
- promgen/tests/test_routes.py
- promgen/tests/test_silence.py
- promgen/tests/test_web.py
- setup.cfg
- Regroup our `GET` only tests into a single test_web file
- Add more coverage for some of our missing pages
> [INTERNAL] Regroup and improve web test cases

- .github/workflows/django.yml
- .github/workflows/docker.yml
- .github/workflows/sphinx.yml
Grouping the initial dependabot upgrades into a single PR
> Dependabot Upgrades

- promgen/views.py
For Service and Project we have a specific set to test about, but when testing site rules (or potentially other types) there is not an expected set of labels we can test against. We need to still declare default expected_labels sets to avoid a Python error.
I ended up doing a little bit of reformatting as well in this PR, but if it's excessive I can redo this as two commits.
> Use default set of expected_labels

- CHANGELOG.md
- pyproject.toml
Cutting a final release from me.
> Release 0.66

- CHANGELOG.md
- pyproject.toml
- [BUGFIX] Misleading =~ operator in silence form #570
- [BUGFIX] Display active silences and rules for service #568
- [IMPROVEMENT] Improve UI/UX of the global list of silence #569
- [BUGFIX] templates/service_detail: Show description #567
> Release 0.67.1

- promgen/static/js/promgen.js
- promgen/templates/base.html
- promgen/templates/promgen/project_detail_hosts_action_button_group.html
- promgen/templates/promgen/sender_row.html
- promgen/views.py
We have added a JS function that allows users to directly access a tab on the UI from a URL if the URL contains a hash with the value being the id of that tab.
> Activate a tab based on the hash value of the URL
